### ISSUE TITLE
TX_news Media link is not generating properly

### ISSUE THREAD

**Issue by Nageshwar** [TYPO3-extensions/news#78] opened 2016-06-01 06:33 UTC
Hello Everyone,
I am getting network error when i want to insert media element using typo3 tx_news 4.0.0 extension.
This error is due to real url which is getting added to the media url and which results video not found.

I am also attaching a snapshot which will give you the exact idea of error.
![bug news 4 0 0](https://cloud.githubusercontent.com/assets/3288042/15700296/cb5ec024-27f0-11e6-88a0-12bbbd0681a3.png)

Please suggest me some way for that

Thanking you

Nageshwar Jha

**Comment by georgringer** [comment] 2016-07-04 17:34
Please test latest version and report again, thx!

**Comment by georgringer** [comment] 2016-07-24 18:19
Are using the non FAL way? please switch to FAL as the other one will be removed sooner then later.

**Comment by georgringer** [comment] 2016-08-01 12:10
duplicate of https://forge.typo3.org/issues/76414

**Closed by georgringer** 2016-08-01 12:10 UTC
Labels: Bug, Needs feedback
